config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tec_noticias.urls'))
]

tec_noticias/urls.py
from django.urls import path

from . import views

app_name = "tec_noticias"

urlpatterns = [
    path('', views.index, name='home'),
    path('home', views.index, name='index'),
    path("sections/<str:num>", views.section, name="section"),
    path("criarComentario",views.comentario_page_view,name="comentario"),
    path('quizz', views.quizz_view, name='quizz'),
    path('guardaContacto', views.guarda_contacto, name='guardaContacto'),
    path('contactoEditar/<str:email>', views.edita_contacto, name='edita_contacto'),
    path('contactoElimina/<str:email>', views.apaga_contacto, name='apaga_contacto'),
    path('login/', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
    path('getNews/',views.Get_Noticias,name="getNews"),
    path('PostarComentario/',views.postarComentarios),
    path('devolveComentarios/<int:id>',views.Get_Comentario_Noticias)
]

tec_noticias/models.py
from django.db import models

# Create your models here.
class Contacto(models.Model):
    nome = models.CharField(max_length=40)
    email = models.CharField(max_length=40)


    def __str__(self):
        return self.nome


class Quizz(models.Model):
    id = models.AutoField(primary_key=True)
    p1 = models.CharField(max_length=10)
    p2 = models.BooleanField()
    p3 = models.DateField()
    p4 = models.TimeField()
    p5 = models.FloatField()
    p6 = models.TextField()
    p7 = models.CharField(max_length=40)
    p8 = models.CharField(max_length=40)
    p9 = models.CharField(max_length=40)
    p10 = models.CharField(max_length=40)

class Comentario(models.Model):
    id = models.AutoField(primary_key=True)
    campo1 = models.CharField(max_length=20)
    campo2 = models.IntegerField(default=20)
    campo3 = models.CharField(max_length=20)
    campo4 = models.CharField(max_length=20)
    campo5 = models.EmailField(max_length=40)
    campo6 = models.BooleanField()
    campo7 = models.CharField(max_length=20)
    campo8 = models.CharField(max_length=20)
    campo9 = models.CharField(max_length=20)
    campo10 = models.TextField(max_length=20)

    def __str__(self):
        return "Nome: " + self.campo1 +  " Idade: " + str(self.campo2) + " Email: " + self.campo5


class Categoria(models.Model):
    tipo = models.CharField(max_length=10)
    #icon = models.CharField(max_length=10)

    def __str__(self):
        return self.tipo

class Noticia(models.Model):
    titulo = models.CharField(max_length=90)
    sinopse = models.CharField(max_length=500)
    imagem = models.CharField(max_length=100)
    autor = models.CharField(max_length=50)
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE,related_name="categoria")
    descricao = models.TextField(max_length=1000)


class Comentario_Noticia(models.Model):
    autor = models.CharField(max_length=100)
    texto = models.TextField(max_length=500)
    data = models.DateField()
    ntc = models.ForeignKey(Noticia,
                           on_delete=models.CASCADE,
                           related_name="Noticia"
                            )

    def __str__(self):
        return "autor: " + self.autor + " texto: "+ self.texto + \
        " data: " + str(self.data)

tec_noticias/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


class contactForm(ModelForm):

    class Meta:
        model = Contacto
        fields = '__all__'


class comentarioNoticiaForm(ModelForm):
    class Meta:
        model = Comentario_Noticia
        fields = ('autor','texto','data')

class QuizzForm(ModelForm):
    class Meta:
        model = Quizz
        fields = '__all__'

        widgets = {
            'p1': forms.TextInput(attrs={'required': True}),
            'p3': forms.DateInput(attrs={'placeholder': 'yyyy:mm:dd'}),
            'p4': forms.TimeInput(attrs={'placeholder': 'hh:mm'}),
        }

        # texto a exibir junto à janela de inserção
        labels = {
            'p1': 'Considera que a apple tem tendencia a ter melhores noticias por ser uma marca de "luxo"?',
            'p2': 'Sabe quais sao os autores do website?',
            'p3': 'Em que data começou PW?',
            'p4': 'E a hora?',
            'p5': 'pi / 2? - com 2 casas decimais',
            'p6': 'Comente o quiz ate agora ( este nao conta !)',
            'p7': 'O Website e de noticias ou de anuncios?',
            'p8': 'Foi Baseado no sapo.pt?',
            'p9': 'Gosta das aulas de PW??',
            'p10': 'Programação ou Gestão de Projetos??',
        }



class ComentarioForm(ModelForm):
    class Meta:
        model = Comentario
        fields = '__all__'

        labels = {
            'campo1': 'Nome',
            'campo2': 'Idade',
            'campo3': 'O website é visualmente atrativo?',
            'campo4':"Cumpre boas praticas de UI/UX?",
            'campo5':'Email?',
            'campo6':'A tablete de Cores condiz',
            'campo7':'O website cumpre as 10 normas de Nielsen?',
            'campo8':'Encontrou algum Bug Grafico ou funcional?',
            'campo9': 'O website tem muitos erros ortográficos?',
            'campo10':'Construtivamente, Aponte o que achou de errado e sugestões de melhoria'
        }

tec_noticias/views.py
import json

from django.contrib.auth import authenticate, login, logout
from django.core import serializers
from django.http import HttpResponseRedirect, HttpResponse, Http404, JsonResponse
from django.shortcuts import render
import matplotlib.pyplot as plt
# Create your views here.
from django.urls import reverse

from .forms import *
from .models import *
from .data import retornaDados
from datetime import date

def index(request):
    comentarioForm = Comentario_Noticia()
    return render(request, "website/home.html",context={'quizz_visible': 'none','comment_visible':'none','comentaForm':comentarioForm})

def section(request, num):
    if num == "comentario":
        form = ComentarioForm()
        context = {
            'form':form
        }
        return render(request,'website/coments.html',context)
    if num == "quizz":
        form = QuizzForm()
        context = {
            'form':form
        }
        return render(request,'website/quizz.html',context)
    if num == "about":
        return render(request,'website/about.html')
    if num == "contactos":
        form = contactForm()
        context = {
            'form': form,
            'contactos': Contacto.objects.all(),
        }
        return render(request,'website/contact.html',context)
    if num == "login":
        return render(request,'website/login.html')
    if num == "home":
        codigo = "<h1> 😄 💻 📱 Vem Vindo a TecNewsTuga ⚽ 🔥</h1>" \
        +        "<p> Esperamos que gostem do nosso website " \
        +         "Feito em Django e em JavaScript usando DOM e outras magias da web....</p> " \
                  "<p>Espero que gostem do website e da sua estrutura." \
                  "Se visualizar erros ou falhas, contacte no formulario comentarios..." \
                  "Esteja sempre informado com a nossa Agencia Noticiaria de Tecnologia !!! </p>"
        return HttpResponse(codigo)
    if num == "apple":
        return HttpResponse("")
    if num == "linux":
        return HttpResponse("")
    if num == "windows":
        return HttpResponse("")
    if num == "showQuizzResults":
        return render(request, "website/home.html", context={'quizz_visible': 'block','pontos':pontos,'comment_visible':'none'})
    if num == "showCommentsResults":
        return render(request, "website/home.html",context={'quizz_visible': 'none','comment_visible': 'block'})
    else:
        raise Http404("No such section")

def guarda_contacto(request):
    form = contactForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('tec_noticias:home'))

    context = {
        'form': form,
        'contactos': Contacto.objects.all(),
    }

    return render(request, 'website/contact.html', context)

def edita_contacto(request, email):
    contacto = Contacto.objects.get(email=email)
    form = contactForm(request.POST or None, instance=contacto)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('tec_noticias:home'))

    context = {'form': form, 'contacto_email': email}
    return render(request, 'website/contact_editar.html', context)

def apaga_contacto(request, email):
    Contacto.objects.get(email=email).delete()
    return HttpResponseRedirect(reverse('tec_noticias:home'))


def comentario_page_view(request):
    form = ComentarioForm(request.POST or None)
    if form.is_valid():
        comentario = form.save()

        comments = Comentario.objects.get(id=comentario.id)
        plt.bar(['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10'],
                [comments.campo1, str(comments.campo2), comments.campo3
                    , comments.campo4, comments.campo5, '' + str(comments.campo6)
                    , comments.campo7, comments.campo8, comments.campo9, comments.campo10])
        plt.savefig('tec_noticias/static/website/imagens/plot_comentario.png', bbox_inches='tight')

        return section(request,'showCommentsResults')

def quizz_view(request):
    form = QuizzForm(request.POST)
    if form.is_valid():
        quizz_form = form.save()
        quizz = Quizz.objects.get(id=quizz_form.id)
        global pontos
        pontos = 0

        respostas_recebidas = [quizz.p1, str(quizz.p2), str(quizz.p3), str(quizz.p4), str(quizz.p5),
                               quizz.p7, quizz.p8, quizz.p9, quizz.p10]

        respostas_certas = ['nao', False, '2021-05-19', '10:00', '1.57', 'noticias', 'nao', 'sim',
                            'gestao de projetos']
        lista_pontos = []

        pontos += 20
        for i in range(0, len(respostas_recebidas)):
            if respostas_recebidas[i] == respostas_certas[i]:
                lista_pontos.append(10)
                pontos += 10
            else:
                lista_pontos.append(0)


        plt.bar(['p1', 'p2', 'p3', 'p4', 'p5', 'p7', 'p8', 'p9', 'p10'], lista_pontos)
        plt.savefig('tec_noticias/static/website/imagens/plot.png', bbox_inches='tight')

        return section(request,'showQuizzResults')


def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(
                    request,
                    username=username,
                    password=password
        )

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('tec_noticias:home'))
        else:
            return render(request, 'website/login.html', {
                'message': 'Credenciais inválidas! Tente Novamente.'
            })

    return render(request, 'website/login.html')

def logout_view(request):
    logout(request)
    return render(request, 'website/home.html', {
        'message': 'Logged out',
        'quizz_visible': 'none',
        'comment_visible':'none'})

def Get_Noticias(request):
    data = list(Noticia.objects.values())
    return JsonResponse(data,safe = False)

def Get_Comentario_Noticias(request,id):
    data = list(Comentario_Noticia.objects.filter(ntc=id).values())
    return JsonResponse(data,safe = False)


def postarComentarios(request):
    if request.method == 'POST':

        id = request.POST.get('id')
        nome = request.POST.get('nome')
        texto = request.POST.get('texto')

        today = date.today()
        data = today.strftime('%Y-%m-%d')

        ntc = Comentario_Noticia(ntc=Noticia(id=id),autor=nome,texto=texto,data=data)
        ntc.save()

        return HttpResponse(
            status=204,
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )

tec_noticias/templates/website/base.html
<!DOCTYPE html>
<html lang="pt">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Tec News">
    <meta name="keywords" content="HTML,Web,Noticias">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Noticas Tec</title>
    {% load static %}
    <script src="{% static 'website/script/singlepage.js' %}"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    {% load static %}
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'website/imagens/icon.svg' %}" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'website/css/base.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
     div {display:none; }


        #botaoSubmit {
            width: 330px;
            height: 25px;
            border-right: seagreen 2px solid;
            box-shadow: 2px 2px 5px black;
        }

        .carrosel {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .carrosel img {
            border-right: aqua solid 1px;
            width: 30%;
            animation-name: animacaoEspecial;
            animation-duration: 6s;
        }

        /* Animacao */
        @keyframes animacaoEspecial {
            25% {
                width: 10%;
            }

            100% {
                font-size: 20px;
                justify-content: stretch;
            }
        }
    </style>
</head>

<body>

    <header>
        <figure class="header_animacao">
            {% load static %}
            <img src="{% static 'website/imagens/header_imagem.svg' %}">
        </figure>

        <figure class="imagemDecorada">
            {% load static %}
            <img src="{% static 'website/imagens/imagemCool.jpg' %}">
        </figure>

        <nav>
            <ul>
                    <li>
                        <a data-section="login" class="about">
                    <i class="fa fa-key" style="font-size:24px;"></i>Fazer Login</a></li>

                <li>
                    <a data-section="home" class="home">
                        <i class="fa fa-home" style="font-size:24px;"></i>
                        Home</a></li>
                <li>
                    <a href="#" class="categoria">
                          <i class="fa fa-newspaper-o" style="font-size:24px;"></i>
                        Categorias </a>
                    <ul>
                        <li><a data-section="apple" class="apple">
                            <i class="fa fa-apple" style="font-size:24px;"></i>
                            Apple</a></li>
                        <li><a data-section="linux" class="linux">
                             <i class="fa fa-linux" style="font-size:24px;"></i>
                            Linux</a></li>
                        <li><a data-section="windows" class="windows">
                             <i class="fa fa-windows" style="font-size:24px;"></i>
                            Windows</a></li>
                    </ul>
                </li>
                <li><a data-section="contactos" class="comments">
                     <i class="fa fa-address-book-o" style="font-size:24px;"></i>Contactos</a></li>
                <li><a data-section="quizz" class="comments">
                    <i class="fa fa-check-square-o" style="font-size:24px;"></i>Quizz</a></li>
                <li><a data-section="comentario" class="comments">
                    <i class="fa fa-commenting" style="font-size:24px;"></i>Comentarios</a></li>
                <li><a data-section="about" class="about">
                    <i class="fa fa-info-circle fa-pulse" style="font-size:24px;"></i>About</a></li>
            </ul>
        </nav>
    </header>

    <main>
        {% block main %}
        <!--
        <section>
            <picture>
                <section class="carrosel">
                    <section>
                        {% load static %}
                        <img src="{% static 'website/imagens/galeria/androidGaleria.jpg' %}">
                        <img src="{% static 'website/imagens/galeria/linux.jpg' %}">
                        <img src="{% static 'website/imagens/galeria/apple.jpg' %}">
                    </section>
                </section>
            </picture>
        </section>

        <section>
    {% for ntc in lista_noticias %}
        </section>
        <ul>
                     <li>
                        <a href="{%  url 'tec_noticias:VerNoticia' ntc.id %}">
                            <h2>
                                <i class="material-icons" style="font-size:36px">{{ ntc.categoria.icon }}</i><br>
                               {{ ntc.titulo }}
                            </h2>
                            <p>{{ ntc.autor }}</p>
                            <br>
                            <figure>
                              <img src={{ntc.imagem}} style="width:50%">
                            </figure>
                            <br>
                            <p>{{ ntc.sinopse }}
                            </p>
                        </a>
                    </li>
               {% endfor %}
        </ul>-->
        {% endblock main %}
    </main>

    <aside>

                     {% if request.user.username %}
                        <h3>ola {{ user.username }}</h3><br>
                        <button type="button" class="btn btn-danger">
                            <a href="{% url 'tec_noticias:logout' %}">Logout</a></button><br>
                        {% else %}
                        <p>Faço Login sff</p>
                    {% endif %}


        <iframe width="350" height="250" src="https://www.youtube.com/embed/hwnP6WSmGhA" title="YouTube video player"
            frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowfullscreen></iframe>
        <!-- formulario-->
        <form action="mailto:email@yourdomain.com" method="POST">
            <label>
                Email para notificações
                <input type="text">
            </label><br>
            <input id="botaoSubmit" type="submit">
        </form>
        <!-- foto estilosa-->
        <figure class="imagemDecorada2">
        {% load static %}
        <img src="{% static 'website/imagens/imagemCool2.jpg' %}">
        </figure>
        <!-- Mais recentes-->
        <ul>
            <p>Noticias mais recentes:</p><br>
            <li> <a style="color:white"
                    href="https://pplware.sapo.pt/microsoft/windows/dica-pesquisar-por-imagens-no-windows-10-siga-estes-passos/">
                    Pesquisade imagens windows</a></li>
            <li> <a style="color:white"
                    href="https://pplware.sapo.pt/truques-dicas/dica-como-saber-o-historico-das-atualizacoes-do-windows-10-rapidamente/">
                    Historico de atualizacoes</a>
            </li>
            <li> <a style="color:white"
                    href="https://pplware.sapo.pt/linux/systemrescuecd-8-0-o-linux-que-pode-salvar-o-windows/">teste
                    ferramenta Linux SystemRescueCD</a></li>
            <li> <a style="color:white"
                    href="https://pplware.sapo.pt/smartphones-tablets/procura-um-iphone-12-iservices-ja-vende-recondicionados/">
                    Iphone 12 - Iservices
                </a>
            </li>
        </ul>
    </aside>

    <footer>
        <!-- Word cloud-->
        <svg width="500" height="300">
            {% load static %}
            <img src="{% static 'website/imagens/wordcloud.jpg' %}" height="90%">
            </image>
            <!-- Outras Paginas-->
            <a href="index.html">
                <rect x="100" y="53" width="86" height="22" style="fill-opacity:0.1" />
            </a>
            <a href="../paginas/linuxNews.html">
                <rect x="100" y="83" width="86" height="22" style="fill-opacity:0.1" />
            </a>

            <a href="../paginas/appleNews.html">
                <rect x="100" y="120" width="86" height="22" style="fill-opacity:0.1" />
            </a>

            <a href="../paginas/androidNews.html">
                <rect x="110" y="160" width="95" height="54" style="fill-opacity:0.1" />
            </a>

            <a href="../paginas/comentario.html">
                <rect x="215" y="118" width="25" height="158" style="fill-opacity:0.1" />
            </a>

            <a href="../paginas/adicionar.html">
                <rect x="246" y="149" width="100" height="75" style="fill-opacity:0.1" />
            </a>

            <a href="../paginas/windowsNews.html">
                <rect x="246" y="230" width="108" height="25" style="fill-opacity:0.1" />
            </a>

            <a href="../paginas/about.html">
                <text x="280" y="120" fill="blue">About</text></a>
        </svg>
    </footer>
</body>

</html>

tec_noticias/templates/website/coments.html
<h3>Comentarios</h3>
<form action="{% url 'tec_noticias:comentario' %}" method="post">
        {% csrf_token %}
        {{ form.as_p  }}
  <input type="submit" value="Gravar" class="btn btn-success" >
</form>

tec_noticias/templates/website/contact.html
<h3>Contactos</h3>

    {% if user.is_authenticated %}
            <form action="{% url 'tec_noticias:guardaContacto' %}" method="post">
        {% csrf_token %}
        {{ form.as_p  }}
        <input type="submit" value="Gravar" class="btn btn-success" >
    </form>


    <p>Lista De Contactos:</p>
    {% for contacto in contactos %}
        <p>
           {{ contacto.nome }}
           <a href="{% url 'tec_noticias:edita_contacto' contacto.email %}" class="btn btn-warning">Editar</a>
           <a href="{% url 'tec_noticias:apaga_contacto' contacto.email %}" role="button" class="btn btn-danger">Apagar</a>
        </p>
   {% endfor %}
    {% else %}
        <p>Faça Login Para Ter acesso aos Contactos</p>
    {% endif %}

tec_noticias/templates/website/contact_editar.html
{% extends 'website/base.html' %}

{% block main %}
<h3>Editar Contacto</h3>

<form action="{% url 'tec_noticias:edita_contacto' contacto_email %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'tec_noticias:home' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
    </form>

{% endblock %}

tec_noticias/templates/website/home.html
{% extends 'website/base.html' %}

{% block main %}
<div id="about"></div>
<div id="home"></div>
<div id="quizz"></div>
<div id="comentario"></div>
<div id="login"></div>
<div id="contactos"></div>
<div id="apple"></div>
<div id="linux"></div>
<div id="windows"></div>
<div id="conteudo">
    <h2 id="noticia_titulo"></h2>
    <h3 id="noticia_data_autor"></h3>
    <img id="noticia_imagem">
    <p id="noticia_texto"></p>
    <form method="POST" id="post-form">
        {% csrf_token %}
        <script>
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

        </script>
        <label>
            Autor
            <input type="text" id="author" required>
        </label><br>
        <label>
            Comentario
            <input type="text" id="commentText" required>
        </label><br>
        <input type="submit" value="Deixar Comentario" class="btn btn-info">
    </form>
    <h2>Comentarios: </h2>
        <ul id="Comment" class="list-group"></ul>
</div>
<!-- Imagem do resultado do quizz gerado por matplotlib -->
<figure id="fig_quizz" style="display: {{ quizz_visible }}">
    <h1 style="display: {{ quizz_visible }}">Resultados do Quizz:</h1>
    {% load static %}
    <img src="{% static 'website/imagens/plot.png' %}">

    {% if pontos < 50 %}
    <p style="color:red;"> 🔵 🔺 Teve {{ pontos }} pontos no total 😢</p>
    {% else %}
    <p style="color:green;"> 🔵 🔺 Teve {{ pontos }} pontos no total 😉 😎</p>
    {% endif %}
</figure>
<!-- Imagem do resultado do comentario gerado por matplotlib -->
<figure id="fig_coments" style="display: {{ comment_visible }}">
    {% load static %}
    <img src="{% static 'website/imagens/plot_comentario.png' %}">
</figure>
{% endblock %}

tec_noticias/templates/website/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

tec_noticias/templates/website/login.html
<h1>Login</h1>
<form action="{% url 'tec_noticias:login' %}" method="post">
            {% csrf_token %}
    <label for="user">Username</label>
    <input type="text" class="table-danger" placeholder="Insira o username..." id="user" name="username"><br>
    <label for="pwd">Password:</label>
    <input type="password" class="table-success" placeholder="Insira a Password" id="pwd" name="password"><br>
    <div class="spinner-border text-danger"></div><br>
  <button type="submit" class="btn btn-primary">Login</button>
</form>

    {% if message %}
        <div> {{ message }} </div>
    {% endif %}

tec_noticias/templates/website/quizz.html
<h3>Quizz</h3>

    <form action="{% url 'tec_noticias:quizz' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Gravar" class="btn btn-success" >
    </form>

    <br>